security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: %admin_password%
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   logout
                target: home

    access_control:
        - { path: /add_game, roles: ROLE_ADMIN }
        - { path: /scheduling, roles: ROLE_ADMIN }
        - { path: /api, roles: ROLE_ADMIN }
        - { path: ^/crud, roles: ROLE_ADMIN }