# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    # keep your service names short
    app.round_results:
        class: AppBundle\Services\RoundResults
        arguments:
            em: @doctrine.orm.entity_manager
    app.round_ranking:
          class: AppBundle\Services\RoundRanking
          arguments:
              em: @doctrine.orm.entity_manager