crud_season:
    resource: "@AppBundle/Resources/config/routing/season.yml"
    prefix:   /crud/season/

crud_player:
    resource: "@AppBundle/Resources/config/routing/player.yml"
    prefix:   /crud/player/

crud_team:
    resource: "@AppBundle/Resources/config/routing/team.yml"
    prefix:   /crud/team/

crud_round:
    resource: "@AppBundle/Resources/config/routing/round.yml"
    prefix:   /crud/round/

crud_game:
    resource: "@AppBundle/Resources/config/routing/game.yml"
    prefix:   /crud/game/

home:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
results:
    path:     /results
    defaults: { _controller: AppBundle:Default:results }
ranking:
    path:     /ranking
    defaults: { _controller: AppBundle:Default:ranking }
scheduling:
    path:     /scheduling
    defaults: { _controller: AppBundle:Default:scheduling }
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
login_check:
    path:     /login_check
logout:
    path:     /logout