AppBundle\Entity\Game:
    type: entity
    table: game
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idRound:
            type: smallint
            nullable: false
            unsigned: false
            column: id_round
        idTeamA:
            type: smallint
            nullable: false
            unsigned: false
            column: id_team_a
        idTeamB:
            type: smallint
            nullable: false
            unsigned: false
            column: id_team_b
        teamAScore:
            type: smallint
            nullable: false
            unsigned: false
            column: team_a_score
        teamBScore:
            type: smallint
            nullable: false
            unsigned: false
            column: team_b_score
    lifecycleCallbacks: {  }
