AppBundle\Entity\Game:
    type: entity
    repositoryClass: AppBundle\Entity\GameRepository
    table: game
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idRound:
            type: integer
            nullable: false
            unsigned: false
            column: id_round
        idTeamA:
            type: integer
            nullable: false
            unsigned: false
            column: id_team_a
        idTeamB:
            type: integer
            nullable: false
            unsigned: false
            column: id_team_b
        teamAScore:
            type: smallint
            nullable: false
            unsigned: false
            column: team_a_score
        teamBScore:
            type: smallint
            nullable: false
            unsigned: false
            column: team_b_score

    manyToOne:
        round:
            targetEntity: Round
            inversedBy: games
            joinColumn:
                name: id_round
                referencedColumnName: id
        team_a:
            targetEntity: Team
            inversedBy: team_a_game
            joinColumn:
                name: id_team_a
                referencedColumnName: id
        team_b:
            targetEntity: Team
            inversedBy: team_b_game
            joinColumn:
                name: id_team_b
                referencedColumnName: id

    lifecycleCallbacks: {  }
