AppBundle\Entity\Player:
    type: entity
    table: player
    id:
        id:
            type: smallint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false


    oneToMany:
        team_player_a:
            targetEntity: Team
            mappedBy: teams_a
        team_player_b:
            targetEntity: Team
            mappedBy: teams_b

    lifecycleCallbacks: {  }
