AppBundle\Entity\Player:
    type: entity
    repositoryClass: AppBundle\Entity\PlayerRepository
    table: player
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false

    oneToMany:
        teams_player_a:
            targetEntity: Team
            mappedBy: player_a
        teams_player_b:
            targetEntity: Team
            mappedBy: player_b

    lifecycleCallbacks: {  }
