AppBundle\Entity\Round:
    type: entity
    repositoryClass: AppBundle\Entity\RoundRepository
    table: round
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idSeason:
            type: integer
            nullable: false
            unsigned: false
            column: id_season
        date:
            type: date
            nullable: true

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: rounds
            joinColumn:
                name: id_season
                referencedColumnName: id

    oneToMany:
        games:
            targetEntity: Game
            mappedBy: round

    lifecycleCallbacks: {  }
