AppBundle\Entity\Round:
    type: entity
    table: round
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idSeason:
            type: smallint
            nullable: false
            unsigned: false
            column: id_season
        date:
            type: date
            nullable: true

    manyToOne:
        season_2_rounds:
            targetEntity: Season
            inversedBy: rounds_2_season
            joinColumn:
                name: id_season
                referencedColumnName: id

    oneToMany:
        games_2_round:
            targetEntity: Game
            mappedBy: round_2_games

    lifecycleCallbacks: {  }
