AppBundle\Entity\Team:
    type: entity
    table: team
    repositoryClass: AppBundle\Entity\TeamRepository
    uniqueConstraints:
        team_combination:
            columns:
                - id_player_a
                - id_player_b
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idPlayerA:
            type: integer
            nullable: false
            unsigned: false
            column: id_player_a
        idPlayerB:
            type: integer
            nullable: false
            unsigned: false
            column: id_player_b
        name:
            type: string
            nullable: true
            length: 45
            fixed: false

    manyToOne:
        player_a:
            targetEntity: Player
            inversedBy: teams_player_a
            joinColumn:
                name: id_player_a
                referencedColumnName: id
        player_b:
            targetEntity: Player
            inversedBy: teams_player_b
            joinColumn:
                name: id_player_b
                referencedColumnName: id

    oneToMany:
        team_a_game:
            targetEntity: Game
            mappedBy: team_a
        team_b_game:
            targetEntity: Game
            mappedBy: team_b

    lifecycleCallbacks: {  }
