AppBundle\Entity\Team:
    type: entity
    table: team
    repositoryClass: AppBundle\Entity\TeamRepository
    uniqueConstraints:
        team_combination:
            columns:
                - id_player_a
                - id_player_b
    id:
        id:
            type: smallint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idPlayerA:
            type: smallint
            nullable: false
            unsigned: false
            column: id_player_a
        idPlayerB:
            type: smallint
            nullable: false
            unsigned: false
            column: id_player_b
        name:
            type: string
            nullable: true
            length: 45
            fixed: false

    manyToOne:
        teams_2_player_a:
            targetEntity: Player
            inversedBy: player_a_2_teams
            joinColumn:
                name: id_player_a
                referencedColumnName: id
        teams_2_player_b:
            targetEntity: Player
            inversedBy: player_b_2_teams
            joinColumn:
                name: id_player_b
                referencedColumnName: id

    oneToMany:
        team_player_a_2_game:
            targetEntity: Game
            mappedBy: games_2_team_a
        team_player_b_2_game:
            targetEntity: Game
            mappedBy: games_2_team_b

    lifecycleCallbacks: {  }
