<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PDO;

/**
 * RoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
	/**
	 * Finds all players participating in one round by round id
	 *
	 * @param $roundId
	 * @return array
	 * @throws \Doctrine\DBAL\DBALException
	 */
    public function findByRoundId($roundId)
    {
        $sql = sprintf(
            '
            SELECT * FROM player WHERE id IN (
                SELECT id_player_a AS id FROM team WHERE id IN (
                    SELECT team.id FROM round r
		            JOIN game AS g ON g.id_round = r.id
		            JOIN team ON team.id = g.id_team_a
		            WHERE r.id = %1$u
		            UNION
		            SELECT team.id FROM round r
		            JOIN game AS g ON g.id_round = r.id
		            JOIN team ON team.id = g.id_team_b
		            WHERE r.id = %1$u
		            ORDER BY id)
	            UNION
	            SELECT id_player_b AS id FROM team WHERE id IN (
                    SELECT team.id FROM round r
		            JOIN game AS g ON g.id_round = r.id
		            JOIN team ON team.id = g.id_team_a
		            WHERE r.id = %1$u
		            UNION
		            SELECT team.id FROM round r
		            JOIN game AS g ON g.id_round = r.id
		            JOIN team ON team.id = g.id_team_b
		            WHERE r.id = %1$u
            	ORDER BY id)
            );
            ', $roundId);

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll(PDO::FETCH_CLASS, 'AppBundle\Entity\Player');
    }
}
