<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PDO;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    /**
     * Retrieves the team object which both player objects are part of
     *
     * @param Player $player1
     * @param Player $player2
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByPlayers(Player $player1, Player $player2) {

        $query = $this->getEntityManager()->createQuery('
              SELECT t, pa, pb FROM AppBundle:Team t
              JOIN t.player_a pa
              JOIN t.player_b pb
              WHERE
                  (t.player_a = :player_1 AND t.player_b = :player_2) OR
                  (t.player_a = :player_2 AND t.player_b = :player_1)')
            ->setParameter('player_1', $player1)
            ->setParameter('player_2', $player2);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
