<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PDO;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    /**
     * Retrieves the team object which both player objects are part of
     *
     * @param Player $playerA
     * @param Player $playerB
     * @return mixed
     * @throws \Doctrine\DBAL\DBALException
     */
    public function findByPlayers(Player $playerA, Player $playerB)
    {
        $sql = sprintf('
            SELECT * FROM team
            WHERE
                (id_player_a = %1$u && id_player_b = %2$u) ||
                (id_player_a = %2$u && id_player_b = %1$u)',
            $playerA->getId(), $playerB->getId());

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $teams = $stmt->fetchAll(PDO::FETCH_CLASS, 'AppBundle\Entity\Team');

        return array_pop($teams);
    }
}
