<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PDO;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function findByPlayerIds($idPlayerA, $idPlayerB)
    {
        $sql = sprintf('
            SELECT * FROM team
            WHERE
                (id_player_a = %1$u && id_player_b = %2$u) ||
                (id_player_a = %2$u && id_player_b = %1$u)',
            $idPlayerA, $idPlayerB);

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        $teams = $stmt->fetchAll(PDO::FETCH_CLASS, 'AppBundle\Entity\Team');

        return array_pop($teams);
    }
}
